name: Update Stats

permissions:
  contents: write # allow workflow to commit & push changes

on:
  schedule:
    - cron: "0 2 * * *" # run every day at 02:00 UTC
  workflow_dispatch: # allow manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stats scripts
        run: |
          python src/version2.py
          python src/log_reader.py
          python src/stats_parser.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add data/weekly/*.json data/weekly/*.csv docs/data/*.json
          git commit -m "Auto-update stats [skip ci]" || echo "No changes to commit"
          git push origin main
